import fs from 'node:fs/promises';
import path from 'node:path';

import { UPLOADS_DIR } from '@/lib/server/paths';

/**
 * Serves an uploaded file.
 *
 * Uploads live on a persistent disk rather than in `public/`, because `public/`
 * is baked into the build — anything written there at runtime disappears on the
 * next deploy. That means they cannot be served as static assets and need this
 * handler instead.
 */

const CONTENT_TYPES = {
  '.jpg': 'image/jpeg',
  '.png': 'image/png',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.pdf': 'application/pdf',
  '.mp4': 'video/mp4',
  '.webm': 'video/webm',
};

export async function GET(request, { params }) {
  const { file } = await params;

  // Stored names are generated by the uploader and always match this shape.
  // Anything else — most importantly anything containing a slash or a `..` —
  // is refused before it can be turned into a path.
  if (!/^[a-z0-9-]+\.[a-z0-9]+$/i.test(file)) {
    return new Response('Not found', { status: 404 });
  }

  const extension = path.extname(file).toLowerCase();
  const contentType = CONTENT_TYPES[extension];
  if (!contentType) return new Response('Not found', { status: 404 });

  try {
    const data = await fs.readFile(path.join(UPLOADS_DIR, file));
    return new Response(data, {
      headers: {
        'Content-Type': contentType,
        'Content-Length': String(data.length),
        // Stored filenames are unique per upload and a file's bytes never
        // change once written, so this can be cached indefinitely. Replacing a
        // photograph produces a new name, which busts the cache by itself.
        'Cache-Control': 'public, max-age=31536000, immutable',
      },
    });
  } catch (error) {
    if (error.code === 'ENOENT') return new Response('Not found', { status: 404 });
    console.error('[media] Failed to read file:', error);
    return new Response('Internal error', { status: 500 });
  }
}
